from application import create_app, db
from application.blueprints.questions.model import Questions
from application.blueprints.scoreboard.model import Scoreboard

app = create_app()

with app.app_context():
    db.drop_all()
    print("Dropping...")
    db.create_all()
    print("Creating...")

    print("Seeding...")

    q1 = Questions(difficulty="easy", question="What is the capital city of France?", answers="['Berlin', 'Paris', 'Rome', 'Madrid']", correct_answer="1")
    q2 = Questions(difficulty="easy", question="What is the capital city of Japan?", answers="['Tokyo', 'Beijing', 'Seoul', 'Bangkok']", correct_answer="0")
    q3 = Questions(difficulty="easy", question="What is the capital city of Brazil?", answers="['Rio de Janeiro', 'São Paulo', 'Brasília', 'Buenos Aires']", correct_answer="2")
    q4 = Questions(difficulty="easy", question="What is the capital city of Australia?", answers="['Sydney', 'Melbourne', 'Canberra', 'Perth']", correct_answer="2")
    q5 = Questions(difficulty="easy", question="What is the capital city of India?", answers="['New Delhi', 'Mumbai', 'Kolkata', 'Bangalore']", correct_answer="0")
    q6 = Questions(difficulty="easy", question="What is the capital city of Canada?", answers="['Toronto', 'Ottawa', 'Vancouver', 'Montreal']", correct_answer="1")
    q7 = Questions(difficulty="easy", question="What is the capital city of South Africa?", answers="['Johannesburg', 'Cape Town', 'Pretoria', 'Durban']", correct_answer="2")
    q8 = Questions(difficulty="easy", question="What is the capital city of Russia?", answers="['Moscow', 'Saint Petersburg', 'Kiev', 'Kazan']", correct_answer="0")
    q9 = Questions(difficulty="easy", question="What is the capital city of Italy?", answers="['Rome', 'Milan', 'Naples', 'Venice']", correct_answer="0")
    q10 = Questions(difficulty="easy", question="What is the capital city of Spain?", answers="['Madrid', 'Barcelona', 'Seville', 'Valencia']", correct_answer="0")
    q11 = Questions(difficulty="easy", question="What is the capital city of Egypt?", answers="['Alexandria', 'Cairo', 'Luxor', 'Giza']", correct_answer="1")
    q12 = Questions(difficulty="easy", question="What is the capital city of Argentina?", answers="['Buenos Aires', 'Santiago', 'Bogota', 'Lima']", correct_answer="0")
    q13 = Questions(difficulty="easy", question="What is the capital city of Germany?", answers="['Berlin', 'Munich', 'Frankfurt', 'Hamburg']", correct_answer="0")
    q14 = Questions(difficulty="easy", question="What is the capital city of China?", answers="['Shanghai', 'Beijing', 'Guangzhou', 'Hong Kong']", correct_answer="1")
    q15 = Questions(difficulty="easy", question="What is the capital city of South Korea?", answers="['Seoul', 'Busan', 'Incheon', 'Daegu']", correct_answer="0")
    q16 = Questions(difficulty="easy", question="What is the capital city of Mexico?", answers="['Mexico City', 'Guadalajara', 'Monterrey', 'Cancun']", correct_answer="0")
    q17 = Questions(difficulty="easy", question="What is the capital city of United Kingdom?", answers="['London', 'Manchester', 'Birmingham', 'Edinburgh']", correct_answer="0")
    q18 = Questions(difficulty="easy", question="What is the capital city of Nigeria?", answers="['Lagos', 'Abuja', 'Kano', 'Ibadan']", correct_answer="1")
    q19 = Questions(difficulty="easy", question="What is the capital city of Turkey?", answers="['Istanbul', 'Ankara', 'Izmir', 'Antalya']", correct_answer="1")
    q20 = Questions(difficulty="easy", question="What is the capital city of Saudi Arabia?", answers="['Riyadh', 'Jeddah', 'Mecca', 'Medina']", correct_answer="0")
    q21 = Questions(difficulty="easy", question="What is the capital city of Kenya?", answers="['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru']", correct_answer="0")
    q22 = Questions(difficulty="easy", question="In which country is the Taj Mahal located?", answers="['India', 'Pakistan', 'Bangladesh', 'Nepal']", correct_answer="0")
    q23 = Questions(difficulty="easy", question="In which country is the Eiffel Tower located?", answers="['Germany', 'France', 'Italy', 'Spain']", correct_answer="1")
    q24 = Questions(difficulty="easy", question="In which country is the Great Wall located?", answers="['China', 'Japan', 'South Korea', 'India']", correct_answer="0")
    q25 = Questions(difficulty="easy", question="In which country is the Statue of Liberty located?", answers="['United Kingdom', 'United States', 'Canada', 'Australia']", correct_answer="1")
    q26 = Questions(difficulty="easy", question="In which country is the Acropolis located?", answers="['Greece', 'Egypt', 'Turkey', 'Italy']", correct_answer="0")
    q27 = Questions(difficulty="easy", question="In which country is the Christ the Redeemer statue located?", answers="['Argentina', 'Brazil', 'Chile', 'Peru']", correct_answer="1")
    q28 = Questions(difficulty="easy", question="In which country is the Sydney Opera House located?", answers="['Australia', 'New Zealand', 'Canada', 'United States']", correct_answer="0")
    q29 = Questions(difficulty="easy", question="In which country is the Colosseum located?", answers="['Italy', 'Greece', 'Spain', 'Turkey']", correct_answer="0")
    q30 = Questions(difficulty="easy", question="In which country is the Petra archaeological site located?", answers="['Egypt', 'Jordan', 'Lebanon', 'Iraq']", correct_answer="1")
    q31 = Questions(difficulty="easy", question="In which country is the Machu Picchu archaeological site located?", answers="['Mexico', 'Brazil', 'Peru', 'Colombia']", correct_answer="2")
    q32 = Questions(difficulty="easy", question="In which country is the Angkor Wat temple complex located?", answers="['Cambodia', 'Vietnam', 'Thailand', 'Myanmar']", correct_answer="0")
    q33 = Questions(difficulty="easy", question="In which country is the Parthenon temple located?", answers="['Italy', 'Greece', 'Spain', 'Turkey']", correct_answer="1")
    q34 = Questions(difficulty="easy", question="In which country is the Sphinx located?", answers="['Egypt', 'Sudan', 'Algeria', 'Libya']", correct_answer="0")
    q35 = Questions(difficulty="easy", question="In which country is the St. Basil's Cathedral located?", answers="['Russia', 'Poland', 'Germany', 'Ukraine']", correct_answer="0")
    q36 = Questions(difficulty="easy", question="In which country is the Palace of Versailles located?", answers="['Spain', 'Italy', 'France', 'Austria']", correct_answer="2")
    q37 = Questions(difficulty="easy", question="In which country is the Forbidden City located?", answers="['China', 'Japan', 'South Korea', 'India']", correct_answer="0")
    q38 = Questions(difficulty="easy", question="In which country is the Tower Bridge located?", answers="['United Kingdom', 'United States', 'Canada', 'Australia']", correct_answer="0")
    q39 = Questions(difficulty="easy", question="In which country is the Sagrada Familia located?", answers="['Spain', 'Portugal', 'France', 'Italy']", correct_answer="0")
    q40 = Questions(difficulty="easy", question="In which country is the Pyramids of Giza located?", answers="['Egypt', 'Sudan', 'Algeria', 'Libya']", correct_answer="0")
    q41 = Questions(difficulty="easy", question="In which country is the Mount Fuji located?", answers="['China', 'Japan', 'South Korea', 'India']", correct_answer="1")
    q42 = Questions(difficulty="easy", question="In which country is the Statue of Christ the Redeemer located?", answers="['Argentina', 'Brazil', 'Chile', 'Peru']", correct_answer="1")

    q43 = Questions(difficulty="medium", question="What is the deepest lake in North America?", answers="['Crater Lake', 'Lake Tahoe', 'Great Slave Lake', 'Lake Superior']", correct_answer="2")
    q44 = Questions(difficulty="medium", question="What is the highest waterfall in North America?", answers="['Multnomah Falls', 'Niagara Falls', 'Yosemite Falls', 'Angel Falls']", correct_answer="1")
    q45 = Questions(difficulty="medium", question="Which river is known as the 'River of Five Colors'?", answers="['Amazon River', 'Cano Cristales', 'Nile River', 'Mekong River']", correct_answer="1")
    q46 = Questions(difficulty="medium", question="What is the largest man-made lake in the United States?", answers="['Lake Mead', 'Lake Okeechobee', 'Lake Powell', 'Lake Erie']", correct_answer="0")
    q47 = Questions(difficulty="medium", question="Which desert is known as the 'White Desert' due to its white chalk rock formations?", answers="['Sahara Desert', 'Gobi Desert', 'Atacama Desert', 'White Desert']", correct_answer="3")
    q48 = Questions(difficulty="medium", question="What is the second largest coral reef system in the world?", answers="['Great Barrier Reef', 'Belize Barrier Reef', 'Maldives Coral Reef', 'Andros Barrier Reef']", correct_answer="1")
    q49 = Questions(difficulty="medium", question="Which mountain range is known as the 'Spine of the Americas'?", answers="['Rocky Mountains', 'Andes', 'Appalachian Mountains', 'Ural Mountains']", correct_answer="1")
    q50 = Questions(difficulty="medium", question="What is the largest island in Indonesia?", answers="['Java', 'Sumatra', 'Borneo', 'Sulawesi']", correct_answer="0")
    q51 = Questions(difficulty="medium", question="Which lake is known as the 'Pearl of Siberia'?", answers="['Lake Baikal', 'Lake Superior', 'Lake Victoria', 'Lake Tanganyika']", correct_answer="0")
    q52 = Questions(difficulty="medium", question="What is the largest saltwater lake in the world?", answers="['Caspian Sea', 'Aral Sea', 'Dead Sea', 'Great Salt Lake']", correct_answer="0")
    q53 = Questions(difficulty="medium", question="Which river is known as the 'Mother of Russia'?", answers="['Volga River', 'Don River', 'Yenisei River', 'Amur River']", correct_answer="0")
    q54 = Questions(difficulty="medium", question="What is the longest mountain range in the world?", answers="['Andes', 'Himalayas', 'Rocky Mountains', 'Alps']", correct_answer="0")
    q55 = Questions(difficulty="medium", question="Which sea is the saltiest in the world?", answers="['Red Sea', 'Dead Sea', 'Caspian Sea', 'Mediterranean Sea']", correct_answer="1")
    q56 = Questions(difficulty="medium", question="What is the largest sand island in the world?", answers="['Fraser Island', 'Baffin Island', 'Prince of Wales Island', 'Victoria Island']", correct_answer="0")
    q57 = Questions(difficulty="medium", question="Which river is known as the 'River of Sorrows'?", answers="['Rio Grande', 'Niger River', 'Amur River', 'Yellow River']", correct_answer="3")
    q58 = Questions(difficulty="medium", question="What is the smallest country in Asia by land area?", answers="['Maldives', 'Singapore', 'Bahrain', 'Brunei']", correct_answer="1")
    q59 = Questions(difficulty="medium", question="Which strait separates Russia and Alaska?", answers="['Bering Strait', 'Davis Strait', 'Taiwan Strait', 'Strait of Gibraltar']", correct_answer="0")
    q60 = Questions(difficulty="medium", question="What is the largest sand desert in the world?", answers="['Sahara Desert', 'Gobi Desert', 'Arabian Desert', 'Rub' al Hali Desert']", correct_answer="2")
    q61 = Questions(difficulty="medium", question="Which river is known as the 'River of Golden Sands'?", answers="['Rio de la Plata', 'Amur River', 'Mekong River', 'Zambezi River']", correct_answer="2")
    q62 = Questions(difficulty="medium", question="What is the largest island in the Mediterranean Sea by land area?", answers="['Sicily', 'Sardinia', 'Cyprus', 'Corsica']", correct_answer="1")
    q63 = Questions(difficulty="medium", question="Which lake is the second largest freshwater lake in the world by volume?", answers="['Lake Superior', 'Lake Baikal', 'Lake Victoria', 'Lake Tanganyika']", correct_answer="0")
    q64 = Questions(difficulty="medium", question="What is the largest island in Japan?", answers="['Honshu', 'Hokkaido', 'Kyushu', 'Shikoku']", correct_answer="0")
    q65 = Questions(difficulty="medium", question="Which river is known as the 'River of Life'?", answers="['Nile River', 'Ganges River', 'Amazon River', 'Mekong River']", correct_answer="1")
    q66 = Questions(difficulty="medium", question="What is the highest active volcano in Europe?", answers="['Mount Vesuvius', 'Mount Etna', 'Stromboli', 'Mount Teide']", correct_answer="1")
    q67 = Questions(difficulty="medium", question="Which sea is bordered by Italy, Croatia, Montenegro, and Albania?", answers="['Adriatic Sea', 'Aegean Sea', 'Ionian Sea', 'Tyrrhenian Sea']", correct_answer="0")
    q68 = Questions(difficulty="medium", question="What is the highest mountain in South America?", answers="['Mount Aconcagua', 'Mount Chimborazo', 'Mount Huascaran', 'Mount Illimani']", correct_answer="0")
    q69 = Questions(difficulty="medium", question="Which country is known as the 'Land of a Thousand Lakes'?", answers="['Finland', 'Sweden', 'Norway', 'Canada']", correct_answer="0")
    q70 = Questions(difficulty="medium", question="What is the largest river in France?", answers="['Loire River', 'Rhone River', 'Seine River', 'Garonne River']", correct_answer="1")

    q71 = Questions(difficulty="hard", question="Which location is furthest south?", answers="['Dubai, United Arab Emirates', 'Karachi, Pakistan', 'Kolkata, India', 'Tehran, Iran']", correct_answer="3")
    q72 = Questions(difficulty="hard", question="Which location is furthest north?", answers="['Bangkok, Thailand', 'Kuala Lumpur, Malaysia', 'Jakarta, Indonesia', 'Hanoi, Vietnam']", correct_answer="3")
    q73 = Questions(difficulty="hard", question="Which location is furthest east?", answers="['Tehran, Iran', 'Riyadh, Saudi Arabia', 'Kuwait City, Kuwait', 'Ankara, Turkey']", correct_answer="1")
    q74 = Questions(difficulty="hard", question="Which location is furthest west?", answers="['Jakarta, Indonesia', 'Manila, Philippines', 'Hanoi, Vietnam', 'Taipei, Taiwan']", correct_answer="3")
    q75 = Questions(difficulty="hard", question="Which location is furthest south?", answers="['Bogota, Colombia', 'Caracas, Venezuela', 'Lima, Peru', 'La Paz, Bolivia']", correct_answer="3")
    q76 = Questions(difficulty="hard", question="Which location is furthest north?", answers="['Buenos Aires, Argentina', 'Santiago, Chile', 'Montevideo, Uruguay', 'Quito, Ecuador']", correct_answer="2")
    q77 = Questions(difficulty="hard", question="Which location is furthest east?", answers="['Bogota, Colombia', 'Caracas, Venezuela', 'La Paz, Bolivia', 'Quito, Ecuador']", correct_answer="3")
    q78 = Questions(difficulty="hard", question="Which location is furthest west?", answers="['Asuncion, Paraguay', 'Montevideo, Uruguay', 'Santiago, Chile', 'Brasilia, Brazil']", correct_answer="2")
    q79 = Questions(difficulty="hard", question="In which country is the city of Ulan Bator located?", answers="['China', 'Mongolia', 'Kazakhstan', 'Russia']", correct_answer="1")
    q80 = Questions(difficulty="hard", question="In which country is the city of Nukus located?", answers="['Kazakhstan', 'Uzbekistan', 'Turkmenistan', 'Kyrgyzstan']", correct_answer="1")
    q81 = Questions(difficulty="hard", question="In which country is the city of Antananarivo located?", answers="['Mauritius', 'Madagascar', 'Seychelles', 'Comoros']", correct_answer="1")
    q82 = Questions(difficulty="hard", question="In which country is the city of Vaduz located?", answers="['Switzerland', 'Liechtenstein', 'Austria', 'Luxembourg']", correct_answer="1")
    q83 = Questions(difficulty="hard", question="In which country is the city of Ouagadougou located?", answers="['Mali', 'Burkina Faso', 'Niger', 'Chad']", correct_answer="1")
    q84 = Questions(difficulty="hard", question="In which country is the city of Bandar Seri Begawan located?", answers="['Brunei', 'Malaysia', 'Indonesia', 'Singapore']", correct_answer="0")
    q85 = Questions(difficulty="hard", question="In which country is the city of Ashgabat located?", answers="['Turkmenistan', 'Kazakhstan', 'Uzbekistan', 'Tajikistan']", correct_answer="0")
    q86 = Questions(difficulty="hard", question="In which country is the city of Ljubljana located?", answers="['Croatia', 'Slovenia', 'Bosnia and Herzegovina', 'Serbia']", correct_answer="1")
    q87 = Questions(difficulty="hard", question="In which country is the city of Thimphu located?", answers="['Bhutan', 'Nepal', 'Bangladesh', 'Myanmar']", correct_answer="0")
    q88 = Questions(difficulty="hard", question="In which country is the city of Bishkek located?", answers="['Kazakhstan', 'Kyrgyzstan', 'Tajikistan', 'Turkmenistan']", correct_answer="1")
    q89 = Questions(difficulty="hard", question="In which country is the city of N'Djamena located?", answers="['Niger', 'Chad', 'Cameroon', 'Benin']", correct_answer="1")
    q90 = Questions(difficulty="hard", question="In which country is the city of Reykjavik located?", answers="['Norway', 'Greenland', 'Iceland', 'Finland']", correct_answer="2")
    q91 = Questions(difficulty="hard", question="In which country is the city of Maputo located?", answers="['Mozambique', 'Angola', 'Zimbabwe', 'Zambia']", correct_answer="0")
    q92 = Questions(difficulty="hard", question="In which country is the city of Maseru located?", answers="['South Africa', 'Lesotho', 'Swaziland', 'Botswana']", correct_answer="1")
    q93 = Questions(difficulty="hard", question="In which country is the city of Libreville located?", answers="['Gabon', 'Congo', 'Equatorial Guinea', 'Central African Republic']", correct_answer="0")
    q94 = Questions(difficulty="hard", question="In which country is the city of Lilongwe located?", answers="['Zambia', 'Malawi', 'Mozambique', 'Tanzania']", correct_answer="1")
    q95 = Questions(difficulty="hard", question="In which country is the city of Yamoussoukro located?", answers="['Ivory Coast', 'Ghana', 'Liberia', 'Senegal']", correct_answer="0")
    q96 = Questions(difficulty="hard", question="In which country is the city of Dushanbe located?", answers="['Tajikistan', 'Kyrgyzstan', 'Turkmenistan', 'Kazakhstan']", correct_answer="0")
    q97 = Questions(difficulty="hard", question="In which country is the city of Gaborone located?", answers="['Zimbabwe', 'Botswana', 'Namibia', 'South Africa']", correct_answer="1")
    q98 = Questions(difficulty="hard", question="In which country is the city of Tegucigalpa located?", answers="['Guatemala', 'El Salvador', 'Honduras', 'Nicaragua']", correct_answer="2")
    q99 = Questions(difficulty="hard", question="In which country is the city of Bujumbura located?", answers="['Rwanda', 'Burundi', 'Uganda', 'Kenya']", correct_answer="1")

    s1 = Scoreboard(username="beef", score="410")

    db.session.add_all([q1,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q2,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q3,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q4,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q5,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q6,q60,q61,q62,q63,q64,q65,q66,q67,q68,q69,q7,q70,q71,q72,q73,q74,q75,q76,q77,q78,q79,q8,q80,q81,q82,q83,q84,q85,q86,q87,q88,q89,q9,q90,q91,q92,q93,q94,q95,q96,q97,q98,q99,s1])

    db.session.commit()